.TH FZY 1 "Jul 9, 2022" "fzy 1.0"
.SH NAME
fzy \- A fuzzy text selector menu for the terminal.
.SH SYNOPSIS
.B fzy
.IR [OPTION]...
.SH DESCRIPTION
.B fzy is a fuzzy text selector/file finder for the terminal using a search
similar to that of TextMate or CmdT.

fzy reads a list of newline-separated items from stdin to be displayed as a
menu in the terminal.
Upon pressing ENTER, the currently selected item is printed to stdout.

Entering text narrows the items using fuzzy matching. Results are sorted using
heuristics for the best match.

.SH OPTIONS
.TP
.BR \-l ", " \-\-lines =\fILINES\fR
How many lines of items to display. If unspecified, defaults to 10 lines.
.
.TP
.BR \-p ", " \-\-prompt =\fIPROMPT\fR
Input prompt (default: '> ')
.
.TP
.BR \-P ", " \-\-pad =\fINUM\fR
Left pad the list of matches NUM places (default: 0)
.
.TP
.BR \-m ", " \-\-multi
Enable multi-selection
.
.TP
.BR \-s ", " \-\-show-scores
Show the scores for each item.
.
.TP
.BR \-t ", " \-\-tty =\fITTY\fR
Use TTY instead of the default tty device (/dev/tty).
.
.TP
.BR \-q ", " \-\-query =\fIQUERY\fR
Use QUERY as the initial search query.
.
.TP
.BR \-e ", " \-\-show-matches =\fIQUERY\fR
Non-interactive mode. Print the matches in sorted order for QUERY to stdout.
.
.TP
.BR \-0 ", " \-\-read-null
Read input delimited by ASCII NUL characters.
.
.TP
.BR \-h ", " \-\-help
Usage help.
.
.TP
.BR \-v ", " \-\-version
Usage help.
.
.TP
.BR \-\-pointer =\fICHAR\fR
Pointer to highlightled match (default '>')
.
.TP
.BR \-\-marker =\fICHAR\fR
Multi-select marker (default '*')
.
.TP
.BR \-\-cyclic
Enable cyclic scrolling
.
.TP
.BR \-\-tab-accetps
TAB accepts: print selection and exit
.
.TP
.BR \-\-right-accepts
Right arrow key accepts: print selection and exit
.
.TP
.BR \-\-left-aborts
Left arrow key aborts: cancel selection and exit
.
.TP
.BR \-\-reverse
List from top, prompt at bottom
.
.TP
.BR \-\-no\-color
Run colorless
.
.SH KEYS
.
.TP
.BR "ENTER"
Print the selected items to stdout and exit. If \fI\-\-right\-accepts\fR is set, the Right arrow key performs the same function. Equally, if \fI\-\-tab\-accepts\fR is set, the TAB key performs the same function.
.TP
.BR "ESC"
Exit without printing any result. If \fI\-\-left\-aborts\fR is set, the Left arrow key performs the same function.
.TP
.BR "Ctrl+c, Ctrl+g, Esc"
Exit with status 1, without making a selection.
.TP
.BR "Up Arrow, Ctrl+p, Ctrl+k"
Select the previous item.
.TP
.BR "Down Arrow, Ctrl+n, Ctrl+j"
Select the next item.
.TP
.BR "TAB"
Replace the current search string with the selected item. If the multi-selection mode (\fI-m, --multi\fR) is enabled, TAB is used to (un)mark the selected entry instead.
.TP
.BR "Backspace, Ctrl+h"
Delete the character before the cursor.
.TP
.BR Ctrl+w
Delete the word before the cursor.
.TP
.BR Ctrl+u
Delete the entire line.
.
.SH COLORS
Interface colors are read from the environment variable \fBFZY_COLORS\fR using a simple pattern: the \fIorder\fR of the color code specifies which \fIinterface element\fR the color must be applied to, while the \fIcontent\fR of this code defines the \fIcolor\fR of this element.
.sp
\fBA\fR. The order is this:
 1) Prompt
 2) Pointer
 3) Marker
 4) Current entry foreground
 5) Current entry background
.sp
\fBB\fR. Possible content (available colors):
 0 = black
 1 = red
 2 = green
 3 = yellow
 4 = blue
 5 = magenta
 6 = cyan
 7 = white
.sp
Use a \fBb\fR before the color to make it bold/bright. A dash (\-) means that the color for the interface element in that position must be skipped.
.sp
For example, \fBFZF_COLORS="\-b1b2\-4"\fR is to be read as follows:
.sp
 \fB\-\fR: no prompt color
 \fBb1\fR: bold red pointer color
 \fBb2\fR: bold green marker color
 \fB\-\fR: no color for the current entry foreground
 \fB4\fR: blue current entry background
.sp
Default colors are: \fBb6b1b2b40\fR
.
.SH USAGE EXAMPLES
.
.TP
.BR "ls | fzy"
Present a menu of items in the current directory
.TP
.BR "ls | fzy \-l 25"
Same as above, but show 25 lines of items
.TP
.BR "vi $(find \-type f | fzy)"
List files under the current directory and open the one selected in vi.
.TP
.BR "cd $(find \-type d | fzy)"
Present all directories under current path, and change to the one selected.
.TP
.BR "ps aux | fzy | awk '{ print $2 }' | xargs kill"
List running processes, kill the selected process
.TP
.BR "git checkout $(git branch | cut \-c 3\- | fzy)"
Same as above, but switching git branches.
.SH AUTHORS
John Hawthorn <john.hawthorn@gmail.com>

L. Abramovich <johndoe.arch@outlook.com>
